package example

import javax.jws.WebService

import org.apache.log4j.Logger;

import example.dto.ObjectFactory
import example.dto.PersonDto
import example.dto.PersonListRequest
import example.dto.PersonListResponse
import example.dto.PersonServicePortType


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(
		name = "PersonService",
		targetNamespace = "http://www.frunix.org/schemas/ws/personList/",
		endpointInterface="example.dto.PersonServicePortType")
class PersonWSService implements PersonServicePortType {

	private static Logger logger = Logger.getLogger(PersonWSService)

	PersonService personService

	private ObjectFactory factory = new ObjectFactory()

	@Override
	PersonListResponse personList(PersonListRequest parameters) {
		logger.info "personList(): invoking"
		List<Person> personsAsList = personService.persons
		PersonListResponse response =
				makePersonListResponseFromPersons(personsAsList)
		response
	}

	PersonListResponse makePersonListResponseFromPersons(
			List<Person> personsAsList)
	{
		logger.info "makePersonListResponseFromPersons(): invoking"
		logger.debug(
			"makePersonListResponseFromPersons(): " +
			"personsAsList: $personsAsList")
		PersonListResponse response = factory.createPersonListResponse()
		response.persons = factory.createPersonListResponsePersons()
		for (Person person : personsAsList) {
			PersonDto personDto = factory.createPerson()
			personDto.id = BigInteger.valueOf(person.id)
			personDto.name = person.name
			personDto.surname = person.surname
			logger.debug(
				"makePersonListResponseFromPersons():" +
				"adding person: $person")
			response.persons.person << personDto
			logger.debug("makePersonListResponseFromPersons():" +
				"total of persons: ${response.persons.person.size()}")
		}
		response
	}


}
