
package example.dto;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "personServicePortType", targetNamespace = "http://www.frunix.org/schemas/ws/personList/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PersonServicePortType {


    /**
     * 
     * @param parameters
     * @return
     *     returns example.dto.PersonListResponse
     */
    @WebMethod(action = "http://www.frunix.org/schemas/ws/personList/personList")
    @WebResult(name = "personListResponse", targetNamespace = "http://www.frunix.org/schemas/personList", partName = "parameters")
    public PersonListResponse personList(
        @WebParam(name = "personListRequest", targetNamespace = "", partName = "parameters")
        PersonListRequest parameters);

}
